### ISSUE TITLE
raspberry 3B在编译汇编文件时缺少宏定义

### ISSUE THREAD

**Issue by Yangxiu123321** [runninglinuxkernel/arm64_programming_practice#1]
rpi3对于串口的初始化`__init_uart`(early_uart.S)，包含了#include "asm/gpio.h"
汇编文件的编译规则如下：
> $(BUILD_DIR)/%_s.o: $(SRC_DIR)/%.S
	$(ARMGNU)-gcc $(ASMOPS) -MMD -c $< -o $@

然而ASMOPS = -g -Iinclude
所以在预处理的时候下面的代码有问题
```
#ifdef CONFIG_BOARD_PI3B
#define PBASE 0x3F000000
#else
#define PBASE 0xFE000000
#endi
```

Makefile需要改为
```
ifeq ($(board), rpi3)
COPS += -DCONFIG_BOARD_PI3B
ASMOPS += -DCONFIG_BOARD_PI3B
QEMU_FLAGS  += -machine raspi3b
else ifeq ($(board), rpi4)
COPS += -DCONFIG_BOARD_PI4B
ASMOPS += -DCONFIG_BOARD_PI4B
QEMU_FLAGS  += -machine raspi4
endif
```

**Comment by runninglinuxkernel** [comment]
Readme.md说了，本实验参考代码 只在树莓派4b上验证过，本书建议在树莓派4b和QEMU上做实验。

树莓派3b很快要停产了，所以，树莓派3b的支持留给 有兴趣的读者 自己完成
