### ISSUE TITLE
求共享打了补丁支持树莓派 4B 的 qemu 源码

### ISSUE THREAD

**Issue by sammyne** [runninglinuxkernel/arm64_programming_practice#2]
希望大佬能够把打了补丁支持树莓派 4B 的 qemu 源码共享一下~

**Comment by hlleng** [comment]
同，请把qemu源码提供出来，方便自己编译

**Comment by runninglinuxkernel** [comment]
我们建议大家使用我们提供的vmware/virtualbox image镜像，这样免去折腾环境的痛苦，把精力集中在做实验上
